#!/bin/bash

# meta-buildpack
#
# Copyright (c) 2015-Present Pivotal Software, Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

cf buildpacks | grep '^meta_buildpack' >/dev/null
META_WAS_INSTALLED=$?

set -e

META_BUILDPACK_DIR=$(cd "$(dirname $0)/.."  && pwd)
TEST_BUILDPACK_DIR=$(cd "$(dirname $0)/test_buildpack" && pwd)
TEST_DECORATOR_DIR=$(cd "$(dirname $0)/test_decorator" && pwd)

(cd $META_BUILDPACK_DIR; ./upload)
(cd $TEST_BUILDPACK_DIR; ./upload)
(cd $TEST_DECORATOR_DIR; ./upload)

TEST_APP_DIR=$(cd "$(dirname $0)/test_app" && pwd)
TEST_RUN_LOG=$(cd "$(dirname $0)/."  && pwd)/run.log

cf delete-org -f meta-buildpack-test
cf create-org meta-buildpack-test
cf target -o meta-buildpack-test
cf create-space test
cf target -s test
(cd $TEST_APP_DIR; ./push 2>&1 | tee $TEST_RUN_LOG)
cf delete-org -f meta-buildpack-test

function cleanup() {
	(cd $TEST_BUILDPACK_DIR; ./delete)
	(cd $TEST_DECORATOR_DIR; ./delete)
	if [ "$META_WAS_INSTALLED" -ne "0" ]; then
		cf delete-buildpack -f meta_buildpack
	fi
}

function assert_present() {
	if ! grep "$1" "$TEST_RUN_LOG" >/dev/null; then
		cleanup
		echo
		echo "FAILED - Output does not contain expected message:" $1
		exit 1
	fi
}

assert_present "^\[meta\-buildpack\] Compiling with test_buildpack"
assert_present "^\[test\-buildpack\] Compiling"
assert_present "^\[meta\-buildpack\] Compiling with test_decorator"
assert_present "^\[test\-decorator\] Compiling"
assert_present "^buildpack: test_buildpack (with decorator test_decorator)"

cleanup

echo
echo "SUCCESS"