#!/bin/bash

SRCDIR=$(cd "$(dirname $0)/."  && pwd)
TGTDIR=$(cd "$(dirname $0)/.." && pwd)
NAME=$(basename "$SRCDIR" | sed s/-/_/g)
ZIPFILE="$TGTDIR/$NAME.zip"

echo "Buildpack name: $NAME"
echo "Source directory: $SRCDIR"
echo "Target file: $ZIPFILE"

rm -f "$ZIPFILE"
zip -r "$ZIPFILE" "$SRCDIR"/lib "$SRCDIR"/bin

cf delete-buildpack -f "$NAME"
cf create-buildpack "$NAME" "$ZIPFILE" 1 --enable
