#!/bin/bash

# meta-buildpack
#
# Copyright (c) 2015-Present Pivotal Software, Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

SRCDIR=$(cd "$(dirname $0)/." && pwd)
TGTDIR=$(cd "$(dirname $0)/." && pwd)
NAME=$(basename "$SRCDIR" | sed s/-/_/g)
ZIPFILE="$TGTDIR/$NAME.zip"

echo "Buildpack name: $NAME"
echo "Source directory: $SRCDIR"
echo "Target file: $ZIPFILE"

rm -f "$ZIPFILE"
(cd "$SRCDIR"; zip -r "$ZIPFILE" lib bin)

cf delete-buildpack -f "$NAME"
cf create-buildpack "$NAME" "$ZIPFILE" 1 --enable
